### ISSUE TITLE
Missing packages.config in UWP project (build fails)

### ISSUE THREAD

**Issue by Simba-Mupfunya** [xamarinhq/app-evolve#1]

**Comment by jamesmontemagno** [comment]
It should still build compile and build. I'll investigate the csproj a bit more tonight, buy inqould see these and it would just deploy anyways. How about for you?

**Comment by Simba-Mupfunya** [comment]
ive been building and testing mobile apps with cordova hybrid(Telerik) and being a hardcore c# developer had considered mono to be a dying breed hence never actually looking into Xamarin (was a premature decision). Three months ago before the integration into the Microsoft family I actually bought an indie licence and began experimenting (if you only new the shock i got). Anyway better late than never, hybrid apps could never quite cut it for me. I'm thrilled you have decided to open source this app as it showcases many features as a real world implementation, so thanks for that.
