### ISSUE TITLE
Windows mobile app doesn't show sessions

### ISSUE THREAD

**Issue by tomkuijsten** [xamarinhq/app-evolve#16]
Im using the WM10 app and it doesn't list any session and it says "No sessions found".

Version 1.1.9

**Comment by jamesmontemagno** [comment]
From the app store or from running the repo? Have you tried to go into the settings and hit the sync button?

**Comment by tomkuijsten** [comment]
Tried it all (refresh in sessions view, sync in settings), nothing works.

**Comment by tomkuijsten** [comment]
Just removed the app and installed again, works fine again. Weird. Some local cache bug I guess. Can be closed,
