### ISSUE TITLE
Search Control does not render for devices running Android 7.0

### ISSUE THREAD

**Issue by MobileRez** [xamarinhq/app-evolve#18]
When running the evolve app on my device running Android 7.0, the submissions page only shows the filter icon and the option to search the list of events is not displayed. 

When I try the same code on a 6.0 device, it works fine. Updating the support libraries and other components with the current code base creates a lot of code breakages so in the apps current iteration, that is not an option unless everything gets updated.

**Comment by jamesmontemagno** [comment]
Google fixed this in 7.1 so not going to worry about too much.
