### ISSUE TITLE
Android project does not build out-of-the-box

### ISSUE THREAD

**Issue by krishermans** [xamarinhq/app-evolve#19]
I downloaded the project (master branch)  and did a rebuild (unloaded the UWP and iOS projects). My setup: VS Studio 2015 Community with Xamarin, all updated to the latest version.

I got 11 Errors, related to `Gcm`, eg. _The type or namespace name 'GcmServiceBase' could not be found (are you missing a using directive or an assembly reference?)_

When I look at the references for the Android project, I see an exclamation mark next to `Microsoft.WindowsAzure.Messaging.Android` and `UrlImageViewHelper`, so these dlls are missing. Any tips on how to fix this?

![Microsoft.WindowsAzure.Messaging.Android](https://cloud.githubusercontent.com/assets/1764769/19145012/2a0c0490-8bad-11e6-9024-3c723e84318c.png)
![UrlImageViewHelper](https://cloud.githubusercontent.com/assets/1764769/19145016/2c2d5a26-8bad-11e6-9dca-204fa2f80519.png)

Thanks for sharing your code with the community, it's great to have insight in a _real_ case!

**Comment by Jhanbury** [comment]
I also have the exact same issue tried updating some packages but no joy :(

**Comment by jamesmontemagno** [comment]
You will need to make sure you log into your Xamarin account to restore components from the component store. 

You can always remove the components and re-add them too.

**Comment by Jhanbury** [comment]
Hi @jamesmontemagno that did the trick thanks for the help!

**Comment by krishermans** [comment]
Indeed, it works now. Thanks!
