### ISSUE TITLE
[Feature Request] Add ASP.NET Admin Website

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarinhq/app-evolve#21]
Currently, data must be manually uploaded or modified in the database. It would be nice to have an ASP.NET admin website that could be deployed for conference admins to add and upload data.

**Comment by manojkulkarni30** [comment]
@jamesmontemagno i would like to contribute for an ASP.NET website

**Comment by roycornelissen** [comment]
Our fork at https://github.com/XpiritBV/app-evolve/ has an ASP.NET MVC Admin app, you could have a look at it here https://github.com/XpiritBV/app-evolve/tree/master/src/DataManager

Like any admin site, it's not very pretty though :) But it did the job for our event.
