### ISSUE TITLE
XamarinEvolve.Clients.Portable won't build

### ISSUE THREAD

**Issue by RobertBernstein** [xamarinhq/app-evolve#23]
I'm using Visual Studio 2015 with all the latest Xamarin components (Tools, Options, Xamarin, Other) installed.  I cannot build XamarinEvolve.Clients.Portable because its .csproj file is looking for  ..\packages\FormsToolkit.1.1.14.  However, the src\XamarinEvolve.Clients.Portable\packages.config file specifies FormsToolkit.1.1.18.

Am I doing something wrong or have others gotten this to build?

Rob

**Comment by ghost** [comment]
I have the same problem.

LP

**Comment by RobertBernstein** [comment]
Thanks, @jamesmontemagno!  In the future, would you prefer I update the NuGet versions myself and submit a pull request?

**Comment by jamesmontemagno** [comment]
Absolutely :) they were updated but the csproj was messed up, which was weird.
