### ISSUE TITLE
The name <name> does not exists in the current context.

### ISSUE THREAD

**Issue by FateAudax** [xamarinhq/app-evolve#25]
Hi, first of all I would like to express my gratitude, and appreciation at the people who made all the xamarin examples and samples.

I downloaded the source code, and read the "Getting Started" that it should be fine building it right out of the box after restoring the NuGet packages. However, I'm getting a few errors such as:

CS0103 The name 'InitializeComponent' does not exists in the current context. 
CS0103 The name 'LabelName' does not exists in the current context. 

The above errors are all occurring in the XamarinEvolve.Clients.UI - CategoryViewCell.xaml.cs file.

In both Android and iOS projects. I'm very new to Xamarin and C#.Net. I am trying XamarinEvolve because I would like to study the codes and see how it all works in a MasterDetail view.

17-Nov-2016:
Update on the issue. After cleaning and rebuilding. Now there's another error which states:

CS0103 The name 'Koush' does not exists in the current context - Xamarin.Android NavigationViewRenderer.cs

**Comment by FateAudax** [comment]
Update on the issue. After cleaning and rebuilding. Now there's another error which states:

CS0103 The name 'Koush' does not exists in the current context - Xamarin.Android NavigationViewRenderer.cs

**Comment by jamesmontemagno** [comment]
Make sure that you are logged into your Xamarin account to restore and install the components in each application.

**Comment by jamesmontemagno** [comment]
See: https://developer.xamarin.com/guides/cross-platform/xamarin-studio/components_walkthrough/
