### ISSUE TITLE
What is the recommended way of editing the UI

### ISSUE THREAD

**Issue by vgvassilev** [xamarinhq/app-evolve#28]
I was wondering how one could visually add controls, it seems that there is no storyboard file in the repo.

**Comment by jamesmontemagno** [comment]
Hey there, the entire app was built with Xamarin.Forms a cross platform UI framework: https://www.xamarin.com/forms

Can read about it here: https://blog.xamarin.com/browse-through-the-evolve-2016-mobile-app-source-code/

I did a retrospective here: http://motzcod.es/post/143599079477/xamarin-evolve-2016-app-development-retrospective
