### ISSUE TITLE
Build issues mostly in GcmService.cs

### ISSUE THREAD

**Issue by dyardyGIT** [xamarinhq/app-evolve#30]
After cleaning & rebuilding each project, still getting issues (build errors) with GcmService.cs I am using vs.net 2017 rc (latest)

It looks like reference Microsoft.WindowsAzure.Messaging.Android is missing as well

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'GcmService.OnMessage(Context, Intent)': no suitable method found to override	XamarinEvolve.Android	C:\Xamarin\evolve\app-evolve-master\src\XamarinEvolve.Android\Notifications\GcmService.cs	98	Active
...
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'WindowsAzure' could not be found (are you missing a using directive or an assembly reference?)	XamarinEvolve.Android	C:\Xamarin\evolve\app-evolve-master\src\XamarinEvolve.Android\Notifications\GcmService.cs	7	Active
...
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'GcmService.OnError(Context, string)': no suitable method found to override	XamarinEvolve.Android	C:\Xamarin\evolve\app-evolve-master\src\XamarinEvolve.Android\Notifications\GcmService.cs	175	Active

**Comment by dyardyGIT** [comment]
I had to add a few components including Koush.UrlImageViewHelper (UrlImageViewHelper) to the Android project.  
In the end I was able to get it to build, by adding in a number of components that were missing/not available in the list of references (including Microsoft.WindowsAzure.Messaging.Android etc.

**Comment by jamesmontemagno** [comment]
You can also try this branch: https://github.com/xamarinhq/app-evolve/tree/remove-components
