### ISSUE TITLE
Auth Service

### ISSUE THREAD

**Issue by shareefalis** [xamarinhq/app-evolve#32]
Hi folks!

We have been looking around for a service but we can't find any docs in Xamarin evolve codebase related to Auth service you use for SSO.  Can you point out how we can get started with that?

Shareef

**Comment by bigtfromaz** [comment]
Shareef,

A few links you might find useful:

https://components.xamarin.com/view/xamarin.auth/

https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users

http://www.joesauve.com/using-xamarin-auth-with-xamarin-forms/

BE CAREFUL HOW and WHERE YOU STORE YOUR APP SECRETS!!!

Tom

**Comment by jamesmontemagno** [comment]
This app specifically is using the legacy Xamarin auth system, which is oAuth 2. Since it is ours we use a nice login page, else xamarin.auth is great.
