### ISSUE TITLE
Build backend issue with VS for Mac

### ISSUE THREAD

**Issue by daspuru** [xamarinhq/app-evolve#33]
Hi,

Trying to build the backend project in VS for mac 7.0 (build 3148) and the following error appears:

/Users/daniel/Documents/Xamarin/app-evolve/src/XamarinEvolve.Backend/XamarinEvolve.Backend.csproj(3,3): Error MSB4019: The imported project "/Library/Frameworks/Mono.framework/Versions/5.0.0/lib/mono/xbuild/Microsoft/VisualStudio/v15.0/WebApplications/Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. (MSB4019) (XamarinEvolve.Backend)

---

The solution is here: http://stackoverflow.com/a/43985605

Thanks.

**Comment by jamesmontemagno** [comment]
Not my bug, already filed in bugzilla
