### ISSUE TITLE
Why in all your apps you do not follow standards James?

### ISSUE THREAD

**Issue by developer9969** [xamarinhq/app-evolve#35]
Hi
I m a seasoned developer (c#/wpf) moving into mobile development and I have downloaded most of  your apps .
Very helpful but i have noticed that standards are not followed

1. Lack of Unit tests
2. Dependency Injections is not done properly( no injection of interfaces in viewmodels or anywhere else)
3.Large use of static classes which makes impossible to test.
4.Static service container ,again difficult to test
5.No suffix for Async methods. 

Please could you clarify whether why you are not following standards?

many thanks

**Comment by Simba-Mupfunya** [comment]
Hi, 

I dont think we should be delving into what coding standards should be or not, as school of thought suggests that this is not the ultimate goal for these show case xamarin applications. We all know how to represent code well (SOLID principles) and im sure James is up there amongst the most competent ones when need be. One can take the code and modify it as needed. You can definitely implement unit testing and the above mentioned without any problems. You even have a xamarin test cloud => https://www.xamarin.com/test-cloud

Have fun with it, xamarin has definitely matured and the way to go with your background
Cheers

**Comment by developer9969** [comment]
Point taken
Apologies,
It was not meant to be disrespectful!!! 
but he is in a position that we all look up to and learn from.
And when we are not sure in a subject we tend to take those examples as gospels..

anyway
APologies again

**Comment by Simba-Mupfunya** [comment]
No need for apologies!!, it was just a opinionated point, and you do have a valid one anyhow. Its
for him to answer as he sees fit I guess. ;-)

**Comment by AlirezaAkbarix** [comment]
Absolutely I Agree with `developer9969` some coders are referencing to these samples for seeing how their apps views, business and architecture should be! look at `Google I/O` app, they release the app lately but they do it completely!
You can find many standard things inside it, but in Evolve there is some issues that can reduce your trustworthy about the whole of project.

**Comment by developer9969** [comment]
@jamesmontemagno  I guess  you said it all by closing this thread without an answer!
