### ISSUE TITLE
The "LinkAssemblies" task failed unexpectedly

### ISSUE THREAD

**Issue by 2010x25** [xamarinhq/app-evolve#43]
Hi James, I am trying to compile the Evolve solution in release mode but getting below error. I am using 
using Visual Studio 2015 and my min Android version is API level 19 and Target version is API level 23. 

**Application is working fine in debug mode.**

![android](https://user-images.githubusercontent.com/7881037/33886710-704de1c4-df82-11e7-8d69-666143355ec6.PNG)

 error MSB4018: The "LinkAssemblies" task failed unexpectedly.
 error MSB4018: Mono.Linker.MarkException: Error processing method: 'System.Void Android.Support.V7.View.WindowCallbackWrapper::n_OnProvideKeyboardShortcuts_Ljava_util_List_Landroid_view_Menu_I(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Int32)' in assembly: 'Xamarin.Android.Support.v7.AppCompat.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Views.KeyboardShortcutGroup
 error MSB4018:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
 error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
 error MSB4018:    at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
 error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance)
 error MSB4018:    at Mono.Linker.Steps.MarkStep.GetOriginalType(TypeReference type)
 error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
 error MSB4018:    at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
 error MSB4018:    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
 error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
 error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
 error MSB4018:    --- End of inner exception stack trace ---
 error MSB4018:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
 error MSB4018:    at Mono.Linker.Steps.MarkStep.Process()
 error MSB4018:    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
 error MSB4018:    at Mono.Linker.Pipeline.Process(LinkContext context)
 error MSB4018:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
 error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
 error MSB4018:    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
 error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
 error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Please help me to check the issue..

**Comment by LucioD3v** [comment]
Hi James, I have the same issue: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void LakinMobile.App/<>c::<.ctor>b__25_2(System.Object,Plugin.FirebasePushNotification.Abstractions.FirebasePushNotificationResponseEventArgs)' in assembly: 'DEMO.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Collections.Generic.IDictionary`2<System.String,System.Object> Plugin.FirebasePushNotification.Abstractions.FirebasePushNotificationResponseEventArgs::get_Data()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	DEMO.Droid	

Can you help me?

**Comment by 2010x25** [comment]
Upgrade your Xamarin version

Kishan

**Comment by LucioD3v** [comment]
Hi Kishan,

I have the last version of Xamarin and the VS 2017, the issue is the same.

Regards!

**Comment by jamesmontemagno** [comment]
Seems to be working for me. I just updated the nugets, but good here.

**Comment by 2010x25** [comment]
It worked for me as well when I updated XamForms Nuget.
What is you  XamForms version ? Also there are dependecies, must update
othet packages as well after upgrading your XamForms version.

Regards
Kishan
