### ISSUE TITLE
Versions deployed to windows store or Android store

### ISSUE THREAD

**Issue by ghost** [xamarinhq/app-evolve#49]
Just wondering if you know where this app is in the stores.

Also does xamarin forms work on macOS ?

**Comment by jamesmontemagno** [comment]
It is no longer in the store no, but you can grab the code and compile.

It should work with macOS, haven't gone through the porting work though.

**Comment by ghost** [comment]
Dumb question. For MacOS would there be any porting needed ? i thought the
whole idea is that VS for Mac and VS for Windows can open the same code and
that Forms is cross platform ?

**Comment by jamesmontemagno** [comment]
Are you asking if the project will open in VS and VS for Mac? Yes!

Are you asking for a macOS head project:
You would need to setup the project, add any missing files, ensure all the plugins and backend services are working properly, add icons. All the UI/business logic would work yes, but still some work to do to.

**Comment by ghost** [comment]
Ok thanks. Still learning the ropes

Cheers

**Comment by jamesmontemagno** [comment]
See: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/mac

**Comment by ghost** [comment]
thanks. I see now why a little bit of c# needs to be written that wraps Cocoa like NSWinow etc.
