### ISSUE TITLE
iOS Fails to build.

### ISSUE THREAD

**Issue by adamhill** [xamarinhq/app-evolve#5]
Fails to build in Alpha channel. (No idea if it is related to that ATM)

VS 2015 Update 2 in Alpha channel fails at the end with:

```

C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(680,3): error : Native linking error: clang: error: no such file or directory: '/Users/adamhill/Library/Caches/Xamarin/mtbs/builds/XamarinEvolveiOS/a0b5d69e48e6689bcfd6f496fc9d6613/obj/iPhone/Debug/mtouch-cache/GoogleAppIndexing'

C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(680,3): warning : References to 'sqlite3' might require additional -framework=XXX or -lXXX instructions to the native linker

C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(680,3): error : Native linking failed. Please review the build log.
```

Package Manager Console is clear. Other iOS apps build fine.

Can someone tell me where more detailed Build logs might be?

**Comment by jamesmontemagno** [comment]
Can you validate that the component from the components folder installed?
You will need to login with your Xamarin account.

**Comment by adamhill** [comment]
How do I validate them?

I can see Azure, Google and Toast in the Components folder, there are no obvious warning symbols on the nodes.

**Comment by jamesmontemagno** [comment]
If you go into the repo folder you will see "Components/" and a bunch of stuff in it. 

Maybe clean/rebuild? 

Full logs can be found: https://developer.xamarin.com/guides/ios/getting_started/installation/windows/connecting-to-mac/troubleshooting/#Log_File_Location
