### ISSUE TITLE
How to hide ListView Separator on the last item like you did in NonScrollableListView?

### ISSUE THREAD

**Issue by viniciusmaia** [xamarinhq/app-evolve#50]
I'm sorry to use this topic for a question like StackOverflow, but I'm trying to create a page like the Info page of iOS conference page, but I have an "error" that I don't know how to resolve and don't Know the best place to ask for a help.

So, my problem is very simple. I use the NonScrollableListView in my app, but in the app conference, at the last item of the ListView, the Separator is hidden and showed only footer divider. I tried use same behaviour at my app, but both Separator and FooterDivider is visible. How can I fix that?

Here is my app result:
![meu app](https://user-images.githubusercontent.com/5260850/38895956-d20cf146-4267-11e8-99e2-f0abaf326db0.png)

The conference app:
![conference app](https://user-images.githubusercontent.com/5260850/38895981-df7ebf58-4267-11e8-92ca-f2b1b1d47472.png)

**Comment by jamesmontemagno** [comment]
I calculate the height manually and subtract 1 pixel :)
