### ISSUE TITLE
Android Startup times

### ISSUE THREAD

**Issue by matteopiccioni** [xamarinhq/app-evolve#53]
Great and nice app,
but in different devices it taske about 8 seconds to start (cold boot)
This thing makes it definitely criticized in a stores where apps need to be reactive and smart.

There any to way to speed up or make splashscreen more interactive (for example with simple animations)

Thanks

**Comment by jamesmontemagno** [comment]
There are several things you can do to make it boot faster. Takes about 4 seconds on my phone or so. You can do animations with Lottie, you can AOT it which will make it start really fast, and ensure linking. The forms teams is always looking to enhance the startup time.
