### ISSUE TITLE
Xamarin.Essentials.Maps

### ISSUE THREAD

**Issue by jimwallery** [xamarinhq/app-evolve#57]
I see in the app-conference source that there is a reference in the VenueViewModel.cs a comment:

 //TODO: Does Xamarin.Essentials support this?

Is this supported yet?  I am trying to convert from a sandbox app using Xamarin.Forms.Maps to Xamarin.Essentials.  If you happen to have a simple sample of how this works from ViewModel to XAML page that would be great.  Alternatively if Essentials does not support if you could let me know an estimated if and when.  Thanks much!

J

**Comment by jamesmontemagno** [comment]
Yup, it does support this: https://docs.microsoft.com/en-us/xamarin/essentials/maps

**Comment by jimwallery** [comment]
James,

Thank you for the prompt response!  I saw that information in the link you provided and incorporated into a sandbox.

I am struggling a bit with how to embed map return information into the XAML page.  All examples I have seen create a new instance of a map through the devices map application.

Does Xamarin.Essentials support the map being embedded in the XAML page or only the launch of the device mapping application?

Thanks again.

Jim

**Comment by jamesmontemagno** [comment]
Hey there, so Xamarin.Essentials Map API is only to launch external map applications. Xamarin.Forms.Maps is the package you are looking for to do maps in general.

**Comment by jimwallery** [comment]
James,
Thanks again for you help, I was getting around to figuring that out…probably not enough coffee yet 😊.
Jim
