### ISSUE TITLE
Deploying backend using VS 2019 Community for Mac

### ISSUE THREAD

**Issue by jWinnaar** [xamarinhq/app-evolve#61]
I understand this project is old; given the developments around Visual Studio. .NET and Xamarin.Forms.

I would like to get this project up and running with backend on Azure; then start updating/modernize it given new developments. I am using VS for Mac (community edition); is it at all possible to use VS for Mac to deploy backend to Azure? If not; how would I go about deploying this backend onto Azure?

Regards, Jonathan

**Comment by DMSeger** [comment]
I deploy my app service backend from my Mac via a Git repo.  https://docs.microsoft.com/en-us/azure/app-service/deploy-local-git

**Comment by FergalMohan** [comment]
I'm also trying to figure out how to get this running with Azure from my Mac and am wondering if deploying the Mobile BackEnd will create a Database where I can add my own Session, Events, Speakers. I'm using VS2019 Mac but probably could switch to my old Windows machine to get access to the integrated "Publish to Azure" options if that would be less painful. Could anyone give me a steer in the right direction ?

**Comment by jamesmontemagno** [comment]
I believe you can only deploy an ASP.NET Core backend from VS for Mac. So the recommended above on deploy local from git would be best.

I will be converting this project to use App Center Data so the backend will actually go away :)
