### ISSUE TITLE
Problem with iOS build

### ISSUE THREAD

**Issue by PaulSnyder** [xamarinhq/app-evolve#7]
I am evaluating Xamarin but can't get the iOS version to build.  All other examples including MyDriving build fine. Thanks

6>C:\Users\Paul\Source\Repos\app-evolve\src\XamarinEvolve.iOS\AppDelegate.cs(14,7,14,19): error CS0246: The type or namespace name 'WindowsAzure' could not be found (are you missing a using directive or an assembly reference?)

6>C:\Users\Paul\Source\Repos\app-evolve\src\XamarinEvolve.iOS\Helpers\Toaster.cs(4,7,4,15): error CS0246: The type or namespace name 'ToastIOS' could not be found (are you missing a using directive or an assembly reference?)

**Comment by jamesmontemagno** [comment]
Please make sure that you have restored all of your nugets and also that you restore the components. You will need to sign into your xamarin account.
