### ISSUE TITLE
iOS fails to build - GoogleAppIndexing

### ISSUE THREAD

**Issue by pcdus** [xamarinhq/app-evolve#8]
Hello,
I can't build the iOS version, whereas the Android version works fine.
I have restored all the NuGets packages, and all the Components seem to be correctly installed.
I get these following errors:

**Native linking failed. Please review the build log.** 
(XamarinEvolve.iOS   //C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets    681)

**Native linking error: file not found: /Users/Xxx/Library/Caches/Xamarin/mtbs/builds/XamarinEvolveiOS/67a3fe1aa3172176a9205b8a492d7e3b/obj/iPhoneSimulator/Debug/mtouch-cache/GoogleAppIndexing**  
(XamarinEvolve.iOS   //C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets    681)

On the Mac, a file "**GoogleAppIndexingResources.bundle**" is present in the given folder.

I don't find any detail in my logs...

Do you have any idea?

**Comment by bigtfromaz** [comment]
Goldstrike,

You probably have a setup issue with your build environment,  You will find that the forums on Xamarin.com is a great place to get help for issues like the one you are describing.

Cheers,

Tom Hebert

**Comment by pcdus** [comment]
Hi Bigfromaz,
I don't found any solution for now.
I've seen that Adamhill met a similar part of my problem, like described here:
[https://github.com/xamarinhq/app-evolve/issues/5](url)
But I don't know if he managed to solve it.
Regards,

**Comment by jamesmontemagno** [comment]
You could maybe maybe just remove the app indexing from the iOS app?
There is just 1 line of code in the AppDelegate

or... delete the component and re-download it? that may work.

**Comment by Beej126** [comment]
removing and re-adding the "Google App Indexing for iOS" component did the trick for me... it had rev'd up from 2.0.2.2 in the project refs to 2.0.3.0 currently... the latter resolved the build error.

for those new to the Xamarin fray, this reference comes via the "Xamarin Components" gallery, similar to Nuget... manage these bits by right mousing on the "Components" node under the iOS target project and select "Edit Components"

![image](https://cloud.githubusercontent.com/assets/6301228/16631419/e9dce3d4-4373-11e6-870c-b17f45aa0593.png)

for mutual reference, i am also seeing numerous phantom "does not exist" errors pop on basic stuff like "InitializeComponent" whenever i open a xaml but they don't prevent a successful build... the iOS app fires up on the simulator and seems to run fine

**Comment by jamesmontemagno** [comment]
Should be good now, but you will still need to log in for components
